### ISSUE TITLE
[Suggestion] 1.16.5 or add viaversion

### ISSUE THREAD

**Issue by Notme11** [MatHax/Legacy#13]
### Describe the feature

cuz some server just being retard and didnt have viaversion

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Matejko06** [comment]
Use MultiConnect or ViaFabric.
