### ISSUE TITLE
[Suggestion] Inventory Walk

### ISSUE THREAD

**Issue by Jacobwasbeast** [MatHax/Legacy#15]
### Describe the feature

You can walk, run, and jump when you have a inventory opened.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Matejko06** [comment]
Already a feature. Its named GUI Move.
