### ISSUE TITLE
[Bug] KillAura 1.17.1

### ISSUE THREAD

**Issue by PalaxiK** [MatHax/Legacy#16]
### Describe the bug

KillAura not working on Piglins and Zombified piglins

### Steps to reproduce

```bash
1.Toggle Killaura
2. Select Piglin and Zombified piglint entities
3. Spawn them/get close to them
```

### MatHax Legacy Version

1.6.5

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Zombified piglins only get attacked when they are attacking you due to ignore passive setting. I found out this setting doesnt work well with piglins tho so thanks for reporting anyway.
