### ISSUE TITLE
[Bug] Crashes with Iris and Sodium installed

### ISSUE THREAD

**Issue by mondjunge** [MatHax/Legacy#25]
### Describe the bug

When I load into my vanilla generated 1.18 survival village with MaxHat 1.18 and Iris&Sodium installed,
Framerate drops immediatly and Game freezes. Eventually it will crash and show this error:

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_265.method_1096(double, double, double)" because "$$6" is null
Exit-Code: -805306369

I can load into the world without Iris&Sodium or without MatHax 1.18 just fine. This seems to be an compatibility issue.

### Steps to reproduce

```bash
Load MatHax 1.18 with Iris and Sodium installed via fabric loader or iris-fabric loader, create new World. Play, the error and framerate drops will occure sooner or later.
```

### MatHax Legacy Version

1.18

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Could i get the whole log?

**Comment by master7720** [comment]
Iris is the problem sodium works fine

**Comment by master7720** [comment]
> ```shell
> iris
> ```

bro dont use legacy on your own world that makes no sense

**Comment by mondjunge** [comment]
> Could i get the whole log?

Client Log: https://pastebin.com/pkVbKN34
Server Log: https://pastebin.com/3iLhE8Gv

**Comment by Matejko06** [comment]
Try using Iris with Sodium as mods,not Iris Fabric Loader.

**Comment by mondjunge** [comment]
Problems do not occure with updated version of MatHax and fabric loader.
