### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Orangeres** [MatHax/Legacy#31]
### Describe the bug

When I was in the end, I turned on anti void. I almost fell off with it on jump mode, so i changed it to flight mode. When I changed anti void to flight, it completely crashed my game, and now I cannot play with this client. I even tried uninstalling and reinstalling

### Steps to reproduce

```bash
Turn on anti void flight mode
```

### MatHax Legacy Version

1.6.6

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
New update will fix this.
