### ISSUE TITLE
[enhancement] MatHax/GhostClient

### ISSUE THREAD

**Issue by QuartzWarrior** [MatHax/Legacy#34]
### Describe the feature

A new client with the same features as MatHax but Ghost like (undetectable cheats only). Like kill aura legit only, etc. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by yeetus-maximus** [comment]
this is for anarchy. bruh

**Comment by QuartzWarrior** [comment]
Well maybe just a module that automatically changes all modules settings to undetectable, or ghostly.
