### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Ryang2v** [MatHax/Legacy#37]
### Describe the bug

Sometimes when i try to enable a hack, it will close all of my hacks and i have to get them all back again

### Steps to reproduce

```bash
I cant, it just happenes randomly and its very annoying.
```

### MatHax Legacy Version

1.5.5

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
![image](https://user-images.githubusercontent.com/67696646/147375418-21ecf170-5c06-495b-b14f-8b2055f95a38.png)
![image](https://user-images.githubusercontent.com/67696646/147375427-d08d088d-e7b5-49c4-b298-6a5b3fe5e525.png)

So you can reproduce it on latest version supported by the installer? (1.6.8)
