### ISSUE TITLE
[Bug] Client Crash on Start

### ISSUE THREAD

**Issue by MythricHD** [MatHax/Legacy#38]
### Describe the bug

After updating to 1.6.8 on 1.18.1 my game crashes instantly.  The only other mod installed is [1.18.1] Fabric API 0.45.0+1.18. 

![K3hpDlXui5](https://user-images.githubusercontent.com/70623476/147376321-0ed5d252-d08a-407c-a19d-b1dc068a7517.png)

Fabric Loader 0.12.12

### Steps to reproduce

```bash
Click the play button.
```

### MatHax Legacy Version

1.6.8

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MythricHD** [comment]
[latest.log](https://github.com/MatHax/Legacy/files/7775398/latest.log)

Here is my log

**Comment by QuartzWarrior** [comment]
Bro same thing happening to me
[latest.log](https://github.com/MatHax/Legacy/files/7775499/latest.log)

**Comment by Matejko06** [comment]
Fixed

**Comment by QuartzWarrior** [comment]
That was way out of context bro
